### ISSUE TITLE
Remove ProjectE branding

### ISSUE THREAD

**Issue by sinkillerj** [FTBTeam/FTB-ProjectEX#100]
Problems resulting from the use of this mod have caused too many issues for the ProjectE team, and frankly I'm surprised that the mod is even still being updated following Latvian's conduct resulting in a Discord ban.

We hereby request the immediate removal of all ProjectE branding from the project name and filenames of this mod. This includes here on Github, as well as on all distribution platforms such as Curseforge. This is not an official addon, nor do we wish to continue being wrongfully associated with it.

Should compliance not be shown we will take all steps necessary to have this mod removed until the change has been made.

**Comment by luigioxx** [comment]
But you have nothing to do but discriminate against a mod? if you don't like it don't install it on your simple mod pack? no? you don't have to ..

**Comment by sinkillerj** [comment]
@luigioxx I will not spend too much time here as you clearly do not understand the situation, but for the sake of clarity I am not a modpack author. I am the leader of the ProjectE team, who is responsible for the development of the ProjectE mod that ProjectEX requires. We expressed in the past that we did not want to be associated with this mod, nor it's author, that never happened. Now that ProjectEX is once again receiving updates it has become a huge issue for us yet again, and as such we are once again requesting that ProjectE be removed from the name of ProjectEX.

**Comment by aAndrew3030** [comment]
@sinkillerj 
Is it really appropriate for you to threaten other mod developers? I don't know what issues you have with the dev, but you could have discussed them in private with them! Also, I doubt you have "official" support, nor asked permission from Mojang or Microsoft, for the ProjectE mod. Threatening other devs is a threat to the Minecraft modding community as a whole. Legal action could mean the end of Minecraft mods, as Microsoft could end this at any time, for any reason.

**Comment by DistantAE** [comment]
@aAndrew3030 I get that you think that its somewhat wrong, but just think about it.

Each update branches off of the main frame of the mod, which in this case is ProjectE.
But the ProjectE team will also need to expand their own tree, they wont be able to add artifical extensions.
When they do grow, there is a possibility that the ProjectEX mod just entirely breaks, and it gets super annoying as its just a repeated cycle.

At least this is what I personally think.

**Comment by DonovanDMC** [comment]
> @aAndrew3030 I get that you think that its somewhat wrong, but just think about it.
> 
> Each update branches off of the main frame of the mod, which in this case is ProjectE. But the ProjectE team will also need to expand their own tree, they wont be able to add artifical extensions. When they do grow, there is a possibility that the ProjectEX mod just entirely breaks, and it gets super annoying as its just a repeated cycle.
> 
> At least this is what I personally think.

Along with this, they don't list anywhere that this isn't an official extension of ProjectE, meanwhile the name portrays it as if it is

**Comment by DonovanDMC** [comment]
> @sinkillerj Is it really appropriate for you to threaten other mod developers? I don't know what issues you have with the dev, but you could have discussed them in private with them! Also, I doubt you have "official" support, nor asked permission from Mojang or Microsoft, for the ProjectE mod. Threatening other devs is a threat to the Minecraft modding community as a whole. Legal action could mean the end of Minecraft mods, as Microsoft could end this at any time, for any reason.

Legal actions between mod developers isn't going to bring down the entire community, and the dev of ProjectE is completely within their bounds to demand removal, as this is a blatant use of their name, acting as if this is officially supported by the ProjectE developers when it clearly isn't, and yet again there also clearly wasn't an agreement beforehand for the naming of this unofficial extension

**Comment by DistantAE** [comment]
> > @sinkillerj Is it really appropriate for you to threaten other mod developers? I don't know what issues you have with the dev, but you could have discussed them in private with them! Also, I doubt you have "official" support, nor asked permission from Mojang or Microsoft, for the ProjectE mod. Threatening other devs is a threat to the Minecraft modding community as a whole. Legal action could mean the end of Minecraft mods, as Microsoft could end this at any time, for any reason.
> 
> Legal actions between mod developers isn't going to bring down the entire community, and the dev of ProjectE is completely within their bounds to demand removal, as this is a blatant use of their name, acting as if this is officially supported by the ProjectE developers when it clearly isn't, and yet again there also clearly wasn't an agreement beforehand for the naming of this unofficial extension

Now heres the thing, whats going to happen to this mod?
Is it gonna just become its own mod? shaping into something new?

Just a question i may as well ask.

**Comment by DonovanDMC** [comment]
> > > @sinkillerj Is it really appropriate for you to threaten other mod developers? I don't know what issues you have with the dev, but you could have discussed them in private with them! Also, I doubt you have "official" support, nor asked permission from Mojang or Microsoft, for the ProjectE mod. Threatening other devs is a threat to the Minecraft modding community as a whole. Legal action could mean the end of Minecraft mods, as Microsoft could end this at any time, for any reason.
> > 
> > Legal actions between mod developers isn't going to bring down the entire community, and the dev of ProjectE is completely within their bounds to demand removal, as this is a blatant use of their name, acting as if this is officially supported by the ProjectE developers when it clearly isn't, and yet again there also clearly wasn't an agreement beforehand for the naming of this unofficial extension
> 
> Now heres the thing, whats going to happen to this mod?
> Is it gonna just become its own mod? shaping into something new?
> 
> Just a question i may as well ask.

By the looks of it, especially now that several months have passed, this mod will likely fade into obscurity as other forks take over and do the same things, but better

**Comment by MichaelHillcox** [comment]
I have updated our Read me on this project and the Curseforge project to state that this is an unofficial extension. Locking and closing

**Comment by MichaelHillcox** [comment]
> Why no, I do not intend to email you @MichaelHillcox. I intend for all communication regarding this issue to be public and transparent, so that everyone can see just how this situation has been handled. Locking an ongoing situation... nice move.
> At this point, I'm done playing nice. Either rename the mod as requested, or remove it. This has gone on for too many years, for too simple of a request.

Could you please reference some of the `too many issues for the ProjectE team`, I'm unaware of any issues at present?

**Comment by sinkillerj** [comment]
Do you plan to comply, or do I need to take this further? I don't know who is running this shit show at this point, and I don't care. If you wanna take over after Latvian, you adopt the problems he caused too, which he was fully aware of when he apparently handed the mod over. 

My terms are clear.

**Comment by MichaelHillcox** [comment]
Your terms can be as clear as you'd like them to be, I've made a simple request for you to evidence your claims.

**Comment by sinkillerj** [comment]
Yes, and ProjectE is my mod, I do not need to explain myself. Rename ProjectEX, or remove it.

When Latvian was banned, he was well aware that this mod was to be renamed. We tried to let it ride since development stopped, but when he released that new build he knew full well what he was doing.

Latvian was always self centered, he would cause issues with his quick hacks, then throw a tantrum when we would not accommodate his hacks. Those same quick hacks have a long history of outright breaking ProjectE, and it's interactions with other addons. 

Latvian was always a profiteer, he could never shut up about it, he did not care about the community, nor the art of creating mods. This unwillingness to just drop this and accept that we don't create for the same reasons was a major reason behind his eventual ban, alongside the aforementioned childish behavior.

By all means, I have no problems with modders making profit from mods they create, but he always went too far. He used the ProjectE name for the same reason he used the FTB name so much, something which clearly your team is too blind to figure out, piggybacking.

**Comment by MichaelHillcox** [comment]
To clarify, I am only a developer for FTB, I do not have final say, you can repeat the fact that we should rename the project as many times as you'd like. But until we've taken time to review the situation properly, consulted our lawyer, and make a final decision, nothing will be actioned upon.

From my point of view, and I speak personally here and not as a representative for FTB, hurt feelings are not enough of a reason to demand a project be renamed, I don't believe you own the word Project nor the letter E. Even more so, I doubt you own the copyright to the name nor the trademark. 

As you've made the request, we will review the situation to the best of our ability. I highly recommend you email us with any evidence you think may strengthen your case to admin@feed-the-beast.com, and you're welcome to CC me in. We're not going to be able to make any progress here. You're welcome to invite me your discord (MiKeY#2628) and we can have a chat in the public space if you'd like to discuss further.

**Comment by sinkillerj** [comment]
Tell me this, what reason do you have to not take the easy resolution. It takes under a minute to rename this repo, and the mod listing. I fully accept that old builds cannot be easily renamed due to Curse limitations. 

I think it speaks volumes of your team's motives if you opt to not take this path, I see why you worked so closely with Latvian.

**Comment by MichaelHillcox** [comment]
Right now, I do not have the permission to do so, I'd need approval before making an action like that. As for my motivation for not wishing to rename the mod: I find it to be an apt name for the mod, it takes ProjectE and extends it, thus ProjectEX. I'm not saying we're not open to renaming the project. I simply can't action upon it yet. 

My comments here have only been stating what would be done and trying to sign post you to the correct places to attempt to resolve the situation. I would not say it speaks volumes to anything other than my willingness to attempt to converse with you politely and to resolve a problem you've brought to us. You can't go around demanding actions and expecting instant results, I'll be sure to update this issue once a final decision has been made. 

Out of curiosity, personally speaking here, how would you feel if the mod was called ProjectX or ProjectZ?

**Comment by sinkillerj** [comment]
This issue was created before FTB took over fully, and the request goes back literal years. I would hardly call that to be a request for instant results. Patience was shown, its gone now.

Ultimately, I would prefer the new name not be that similar. The idea is to disconnect from a bad actor.

**Comment by MichaelHillcox** [comment]
I appreciate that, but only as of my first reply was I made aware of this issue, and thus I'm talking from that point onwards.

If the intention is to simply separate away from the bad actor (as you call them), this as already been done. LatvianModder no longer has anything to do with this project.

**Comment by sinkillerj** [comment]
I can understand that but at the same time, you took a position of authority to not only close an issue that anyone could see was touchy, but to lock it.

As long as the name stays as it is, the motives stay the same as his. I've respected FTB for many many years, but this experience has been eye opening.

**Comment by MichaelHillcox** [comment]
I closed the issue as from my point of view, the problem was dealt with, I had updated the Read Me of the project to make it clear the projects are unrelated. I had locked the issue as requests like these should really go to our email, and thus I forwarded you there. The moment you noted that you would like to handle this publicly, I reopen and unlocked the issue. 

I don't believe that the reputation of one person is carried over to all of their projects. If someone took over KubeJS, would you be requesting to rename it? I know the parallel isn't direct here, but you can likely see my point. I apologize if you have disagreed with how I've handled this thus far, but I hope we can continue to work it out.

**Comment by LatvianModder** [comment]
skill issue
